### ISSUE TITLE
Roadmap (dynamically changing)

### ISSUE THREAD

**Issue by gianzellweger** [gianzellweger/badlang#3]
# Features:
- [x] Updates
- [x] Account
- [x] Trial/Subscription System
- [x] Server outages
- [x] Required Internet
- [x] Location services
- [x] Ads
- [x] Mailing List
- [x] Cookies
- [x] TOS
- [x] Dependency Spam
- [ ] Popup-Video
- [ ] Working subscriptions
- [ ] Working mailing list
- [ ] Working location services

_Originally posted by @gianzellweger in https://github.com/gianzellweger/badlang/issues/2#issuecomment-1870684955_

**Comment by gianzellweger** [comment]
Feel free to post more ideas to mimic everything that is a bit silly about today's society, especially modern games and the modern web.
